### ISSUE TITLE
Add more info about where the project should be created: relative, absolute

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/scaffold-command#4]
### Proposition

Add more info about where the project should be created (relative, absolute) as the existing command is not really verbose about that

```
? Where should we create your new project 
X Sorry, your reply was invalid: Value is required
```

**Comment by metacosm** [comment]
The current version is actually more explicit: `"Project location (immediate child directory of %s)"`

**Comment by metacosm** [comment]
Fixed in latest version.
